export const CATEGORY_LABELS = {
  groceries: 'Продукты',
  dining: 'Кафе',
  cafes: 'Кофейни и кофе',
  delivery: 'Доставка еды',
  alcohol: 'Алкоголь',
  tobacco: 'Табак и вейпы',
  household: 'Бытовые товары',
  home: 'Дом',
  furniture: 'Мебель и декор',
  appliances: 'Бытовая техника',
  electronics: 'Электроника',
  software: 'Программы и приложения',
  subscriptions: 'Подписки',
  rent: 'Аренда жилья',
  utilities: 'Коммунальные услуги',
  internet: 'Интернет и связь',
  transport: 'Транспорт',
  public_transport: 'Общественный транспорт',
  taxi: 'Такси',
  fuel: 'Топливо',
  parking: 'Парковка и платные дороги',
  car: 'Автомобиль и обслуживание',
  travel: 'Путешествия',
  accommodation: 'Проживание',
  health: 'Здоровье',
  pharmacy: 'Аптека',
  beauty: 'Красота и уход',
  clothing: 'Одежда',
  shoes: 'Обувь',
  children: 'Дети',
  pets: 'Питомцы',
  entertainment: 'Развлечения',
  sports: 'Спорт',
  education: 'Образование',
  books: 'Книги и пресса',
  gifts: 'Подарки',
  charity: 'Благотворительность',
  banking: 'Банковские услуги',
  taxes: 'Налоги и пошлины',
  services: 'Услуги',
  office: 'Канцтовары',
  other: 'Другое',
} as const

export type Category = keyof typeof CATEGORY_LABELS
export const CATEGORY_KEYS = Object.keys(CATEGORY_LABELS) as [Category, ...Category[]]
